// Auto-generated by schema type watcher. Do not edit manually.

export interface TestCapsuleData {
	eyebrow?: string;
	eyebrowHref?: string;
	title: string;
	description?: string;
	primaryCtaLabel?: string;
	secondaryCtaLabel?: string;
	imageSrc?: string;
	imageAlt?: string;
}
