// Auto-generated by schema type watcher. Do not edit manually.

export interface TestCapsuleData {
	eyebrow?: string;
	eyebrowHref?: string;
	title: string;
	showDescription?: boolean;
	description?: string;
	richDescription?: string;
	primaryCtaLabel?: string;
	secondaryCtaLabel?: string;
	imageSrc?: string;
	imageAlt?: string;
	longDescription?: string;
	bio?: string;
	featured?: boolean;
	active: boolean;
	country?: string;
	framework?: string;
}
