// Auto-generated by schema type watcher. Do not edit manually.

export interface GlobalVariablesData {
	siteName: string;
	siteEmail?: string;
	siteDescription?: string;
	facebookUrl?: string;
	twitterUrl?: string;
	instagramUrl?: string;
	linkedinUrl?: string;
	youtubeUrl?: string;
	phone?: string;
	email?: string;
	address?: string;
	city?: string;
	country?: string;
}
