// Auto-generated by schema type watcher. Do not edit manually.

export interface PrototypeSchemaData {
	title: string;
	description?: string;
	published?: boolean;
	category?: string;
	accentColor?: string;
	backgroundColor?: string;
	themeColor?: string;
}
