// Auto-generated by schema type watcher. Do not edit manually.

export interface ValidationTestsData {
	title: string;
	showCta?: boolean;
	ctaLabel?: string;
	ctaUrl?: string;
	contactEmail?: string;
	price?: number | null;
	seats?: number | null;
	slug?: string;
	apiKey?: string;
	audience?: string;
	membersNote?: string;
	summary?: string;
	speakers: ValidationTestsSpeakerItem[];
}

export interface ValidationTestsSpeakerItem {
	_id: string;
	name: string;
	hasWebsite?: boolean;
	website?: string;
}
