// Auto-generated by schema type watcher. Do not edit manually.

export interface SelectTestsData {
	country?: any;
	priority: any;
	theme?: any;
	framework?: any;
	language?: any;
	plan?: any;
	deployment?: any;
	city?: any;
	animal?: any;
	linkedPage?: any;
	linkedPageGrouped?: any;
	status: any;
	emptyField?: any;
	color?: any;
	ingredient?: any;
	noColumns?: any;
	twoColumns?: any;
	threeColumns?: any;
	responsiveColumns?: any;
	groupedColumns?: any;
	colSpanFull?: any;
	highlightMatches?: any;
	notes?: string;
}
