// Auto-generated by schema type watcher. Do not edit manually.

export interface SelectTestsData {
	country: string;
	tags?: string[];
	regions?: string[];
	skills?: string[];
	categories: string[];
	priority: string;
	theme?: string;
	framework?: string;
	language?: string;
	plan?: string;
	deployment?: string;
	city?: string;
	animal?: string;
	linkedPage?: string;
	linkedPageGrouped?: string;
	status: string;
	emptyField?: string;
	color?: string;
	ingredient?: string;
	noColumns?: string;
	twoColumns?: string;
	threeColumns?: string;
	responsiveColumns?: string;
	groupedColumns?: string;
	colSpanFull?: string;
	highlightMatches?: string;
	notes?: string;
}
