import fs from "node:fs/promises";
import path from "node:path";
import { getInterfaceName, normalizeInterfaceStem, parseSchemaFile } from "./parse-schema";
import type {
	BatchProcessSummary,
	FileWriteResult,
	GeneratedDtsFile,
	ParsedSchemaDefinition,
	ParsedSchemaField,
	ProcessSchemaResult
} from "./types";

function toDtsPath(schemaPath: string): string {
	return schemaPath.replace(/\.schema\.ts$/, ".schema.d.ts");
}

/**
 * Renders the field lines of an interface. Each repeater adds an item interface to
 * `itemInterfaces`, named `<stem><ItemName or FieldName>Item` (nested ones extend the stem).
 */
function renderFieldLines(fields: ParsedSchemaField[], stem: string, itemInterfaces: string[]): string[] {
	return fields.map((field) => {
		let type = field.type;
		if (field.children) {
			const itemStem = `${stem}${normalizeInterfaceStem(field.itemName ?? field.name)}`;
			const itemInterface = `${itemStem}Item`;
			const lines = ["\t_id: string;", ...renderFieldLines(field.children, itemStem, itemInterfaces)];
			itemInterfaces.push([`export interface ${itemInterface} {`, ...lines, `}`].join("\n"));
			type = `${itemInterface}[]`;
		}
		const optionalFlag = field.required ? "" : "?";
		return `\t${field.name}${optionalFlag}: ${type};`;
	});
}

function renderInterface(schema: ParsedSchemaDefinition): string {
	const interfaceName = getInterfaceName(schema);
	const itemInterfaces: string[] = [];
	const fields = renderFieldLines(schema.fields, interfaceName.replace(/Data$/, ""), itemInterfaces).join("\n");

	return [
		[`export interface ${interfaceName} {`, fields || "\t// No fields detected yet.", `}`].join("\n"),
		...itemInterfaces
	].join("\n\n");
}

function generateDtsFromSchemaFile(schemaPath: string): GeneratedDtsFile {
	const parsed = parseSchemaFile(schemaPath);
	const interfaces = parsed.schemas.map((schema) => renderInterface(schema)).join("\n\n");

	const content = [
		"// Auto-generated by schema type watcher. Do not edit manually.",
		"",
		interfaces || "export type __SchemaTypesGenerationPlaceholder = never;",
		""
	].join("\n");

	return {
		path: toDtsPath(schemaPath),
		content
	};
}

async function writeFileIfChanged(filePath: string, content: string): Promise<FileWriteResult> {
	let previous: string | null = null;
	try {
		previous = await fs.readFile(filePath, "utf8");
	} catch {
		previous = null;
	}

	if (previous === content) {
		return "skipped";
	}

	const parentDir = path.dirname(filePath);
	await fs.mkdir(parentDir, { recursive: true });
	const tempPath = `${filePath}.tmp`;
	await fs.writeFile(tempPath, content, "utf8");
	await fs.rename(tempPath, filePath);
	return "written";
}

async function processSchemaFile(schemaPath: string): Promise<ProcessSchemaResult> {
	try {
		const parsed = parseSchemaFile(schemaPath);
		const generated = generateDtsFromSchemaFile(schemaPath);
		const result = await writeFileIfChanged(generated.path, generated.content);
		const fieldCount = parsed.schemas.reduce((acc, schema) => acc + schema.fields.length, 0);

		return {
			status: "success",
			filePath: schemaPath,
			outputPath: generated.path,
			result,
			schemaCount: parsed.schemas.length,
			fieldCount
		};
	} catch (error) {
		return {
			status: "error",
			filePath: schemaPath,
			error: error instanceof Error ? error : new Error(String(error))
		};
	}
}

export async function processSchemaBatch(schemaPaths: string[]): Promise<BatchProcessSummary> {
	const results: ProcessSchemaResult[] = [];

	for (const schemaPath of schemaPaths) {
		results.push(await processSchemaFile(schemaPath));
	}

	const summary: BatchProcessSummary = {
		processed: results.length,
		written: results.filter(
			(result) => result.status === "success" && result.result === "written"
		).length,
		skipped: results.filter(
			(result) => result.status === "success" && result.result === "skipped"
		).length,
		failed: results.filter((result) => result.status === "error").length,
		results
	};

	return summary;
}
