// Auto-generated by schema type watcher. Do not edit manually.

export interface RepeaterTestsData {
	heading?: string;
	cards: RepeaterTestsCardItem[];
	stats: RepeaterTestsStatItem[];
	faq: RepeaterTestsSectionItem[];
	buttons: RepeaterTestsButtonItem[];
}

export interface RepeaterTestsCardItem {
	_id: string;
	title: string;
	body?: string;
	image?: string[];
}

export interface RepeaterTestsStatItem {
	_id: string;
	value?: string;
	label?: string;
}

export interface RepeaterTestsSectionQuestionItem {
	_id: string;
	question?: string;
	answer?: string;
}

export interface RepeaterTestsSectionItem {
	_id: string;
	section?: string;
	questions: RepeaterTestsSectionQuestionItem[];
}

export interface RepeaterTestsButtonItem {
	_id: string;
	label?: string;
	href?: string;
	variant?: string;
	external?: boolean;
	accent?: string;
}
