// Auto-generated by schema type watcher. Do not edit manually.

export interface FileUploadTestsData {
	avatar?: string[];
	cover: string[];
	gallery?: string[];
	attachments?: string[];
	caption?: string;
}
