import fs from "node:fs/promises";
import path from "node:path";
import { getInterfaceName, parseSchemaFile } from "./parse-schema";
import type {
	BatchProcessSummary,
	FileWriteResult,
	GeneratedDtsFile,
	ParsedSchemaDefinition,
	ProcessSchemaResult
} from "./types";

function toDtsPath(schemaPath: string): string {
	return schemaPath.replace(/\.schema\.ts$/, ".schema.d.ts");
}

function renderInterface(schema: ParsedSchemaDefinition): string {
	const interfaceName = getInterfaceName(schema);
	const fields = schema.fields
		.map((field) => {
			const optionalFlag = field.required || field.hasDefaultValue ? "" : "?";
			return `\t${field.name}${optionalFlag}: ${field.type};`;
		})
		.join("\n");

	return [`export interface ${interfaceName} {`, fields || "\t// No fields detected yet.", `}`].join(
		"\n"
	);
}

export function generateDtsFromSchemaFile(schemaPath: string): GeneratedDtsFile {
	const parsed = parseSchemaFile(schemaPath);
	const interfaces = parsed.schemas.map((schema) => renderInterface(schema)).join("\n\n");

	const content = [
		"// Auto-generated by schema type watcher. Do not edit manually.",
		"",
		interfaces || "export type __SchemaTypesGenerationPlaceholder = never;",
		""
	].join("\n");

	return {
		path: toDtsPath(schemaPath),
		content
	};
}

export async function writeFileIfChanged(filePath: string, content: string): Promise<FileWriteResult> {
	let previous: string | null = null;
	try {
		previous = await fs.readFile(filePath, "utf8");
	} catch {
		previous = null;
	}

	if (previous === content) {
		return "skipped";
	}

	const parentDir = path.dirname(filePath);
	await fs.mkdir(parentDir, { recursive: true });
	const tempPath = `${filePath}.tmp`;
	await fs.writeFile(tempPath, content, "utf8");
	await fs.rename(tempPath, filePath);
	return "written";
}

export async function processSchemaFile(schemaPath: string): Promise<ProcessSchemaResult> {
	try {
		const parsed = parseSchemaFile(schemaPath);
		const generated = generateDtsFromSchemaFile(schemaPath);
		const result = await writeFileIfChanged(generated.path, generated.content);
		const fieldCount = parsed.schemas.reduce((acc, schema) => acc + schema.fields.length, 0);

		return {
			status: "success",
			filePath: schemaPath,
			outputPath: generated.path,
			result,
			schemaCount: parsed.schemas.length,
			fieldCount
		};
	} catch (error) {
		return {
			status: "error",
			filePath: schemaPath,
			error: error instanceof Error ? error : new Error(String(error))
		};
	}
}

export async function processSchemaBatch(schemaPaths: string[]): Promise<BatchProcessSummary> {
	const results: ProcessSchemaResult[] = [];

	for (const schemaPath of schemaPaths) {
		results.push(await processSchemaFile(schemaPath));
	}

	const summary: BatchProcessSummary = {
		processed: results.length,
		written: results.filter(
			(result) => result.status === "success" && result.result === "written"
		).length,
		skipped: results.filter(
			(result) => result.status === "success" && result.result === "skipped"
		).length,
		failed: results.filter((result) => result.status === "error").length,
		results
	};

	return summary;
}
