// Modules generated by the Capsulo integration (integration/virtual-modules.ts) from the site's files.
declare module "virtual:capsulo/config" {
	const capsuloConfig: import("../lib/config/define-config").CapsuloConfig;
	export default capsuloConfig;
}

declare module "virtual:capsulo/globals-schema" {
	/** `globalsSchema` from the site's `src/config/globals/globals.schema.ts` (empty if it has none). */
	export const globalsSchema: import("../lib/form-builder/core/types").SchemaDefinition;
}

declare module "virtual:capsulo/capsules" {
	/** Every `capsule.definition.ts` under the site's `src/components/capsules`, keyed by path. */
	const modules: Record<string, Record<string, unknown>>;
	export default modules;
}

declare module "virtual:capsulo/capsule-schemas" {
	/** Every `*.schema.ts` under the site's `src/components/capsules`, keyed by path. */
	const modules: Record<string, Record<string, unknown>>;
	export default modules;
}
