// Auto-generated by schema type watcher. Do not edit manually.

export interface ColorPickerTestsData {
	brandColor?: string;
	primaryColor?: string;
	requiredColor: string;
	overlayColor?: string;
	statusColor?: string;
	accentColor?: string;
	themeColor?: string;
	titleColor?: string;
	alertColor: string;
	bannerOverlay: string;
	heroTint: string;
	neutralTone?: string;
	warmAccent?: string;
	coolAccent?: string;
	linkColor?: string;
	notes?: string;
}
